# Generated by Django 5.1.4 on 2024-12-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_file", models.FileField(upload_to="videos/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subtitle_file",
                    models.FileField(blank=True, null=True, upload_to="subtitles/"),
                ),
                (
                    "output_video",
                    models.FileField(blank=True, null=True, upload_to="outputs/"),
                ),
            ],
        ),
    ]
